version : '3'

services:
  my-website:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image : "redis:7.2.4"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./cfg/redis.conf:/usr/local/etc/redis/redis.conf


